config/routes.rb
Rails.application.routes.draw do
  root to: "notes#index"
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :notes do
    member do
      put :note_permissions
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
	ACTIONS = %i[viewable editable deletable]
	PERMITTED_PARAMS = [:id, :title, :description, tag_ids: []]

	has_many :taggings
	has_many :note_permissions
  has_many :tags, through: :taggings

  belongs_to :user


  def applicable_actions(current_user_id)
  	return ACTIONS if self.user_id == current_user_id
  	user_note_permission = self.note_permissions.find_by(user_id: current_user_id)
  	return [] if user_note_permission.blank?
  	ACTIONS.select{|action| user_note_permission.send(action)}
  end
end

app/models/note_permission.rb
class NotePermission < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
  has_many :notes, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :note
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes
  has_many :note_permissions

  def related_notes_ids
    related_notes_ids = self.notes.ids
    related_notes_ids << self.note_permissions.where("viewable OR editable OR deletable").pluck(:note_id)
    related_notes_ids.flatten
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

	def after_sign_in_path_for(resource)
    if user_signed_in?
      notes_path
    else
      root_path
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :find_note, only: %i[edit update destroy]

  def new
    @note = Note.new
  end

  def create
    note = current_user.notes.new(note_params)
    if note.save
      redirect_to notes_path, notice: 'Note was successfully created.'
    else
      redirect_to notes_path, alert: get_error_messages(note).to_s
    end
  end

  def index
    @tags = Tag.all
  end

  def edit; end

  def update
    if @note.update(note_params)
      redirect_to notes_path, notice: 'Note was successfully updated.'
    else
      redirect_to notes_path, alert: get_error_messages(@tax).to_s
    end
  end

  def destroy
    if @note.destroy
      redirect_to notes_path, notice: 'Note was successfully deleted.'
    else
      redirect_to notes_path, alert: get_error_messages(@tax).to_s
    end
  end

  def note_permissions
    note_permission = NotePermission.find_or_create_by(user_id: params[:user_id], note_id: params[:note_id])
    note_permission.update(permission_params)
    redirect_to notes_path, notice: 'Permission successfully created.'
  end

  private

  def find_note
    @note = Note.find_by(id: params[:id])
    redirect_to notes_path, alert: 'Note was not found.' unless @note.present?
  end

  def note_params
    params.require(:note).permit(Note::PERMITTED_PARAMS)
  end

  def permission_params
    params.permit(:viewable, :editable, :deletable)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
    when 'notice' then 'alert-success'
    when 'success' then 'alert-success'
    when 'error' then 'alert-error'
    when 'alert' then 'alert-error'
    end
  end

  def form_button_text
    case controller.action_name
    when 'new'
      'Save'
    when 'edit'
      'Update'
    else
      'Submit'
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
	def tags_data(obj)
		obj.tags.present? ? obj.tags.pluck(:name).join('<br>') : '-'
	end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, class: "#{flash_class(key)} p-3 w-100 rounded alert alert-header-msg" do %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
    </button>
    <%= value %>
  <% end %>
<% end %>
<% flash.clear %>
<script type="text/javascript">
  $(".alert-header-msg").fadeOut(4000);
</script>

app/views/layouts/_footer.html.erb
<% if current_user.present? %>
  <footer class="main-footer fixed">
    <div class="d-lg-flex align-items-center justify-content-between">
      <div class="foot-nav d-flex flex-column flex-md-row">
        <%= link_to 'Terms', "javascript:", class: 'mb-1 mb-md-0' %>
        <%= link_to 'Privacy Policy', "javascript:", class: 'mb-1 mb-md-0' %>
        <!--  <a href="javascript:;" class="mb-1 mb-md-0">Product Suggestions</a> -->
      </div>
      <p class="copy-text text-darkgray1 mt-3 mt-lg-0">&copy;Note <span class="footer_date"></span> All rights reserved.
      </p>
    </div>
  </footer>
<% end %>

app/views/layouts/_header.html.erb
<% if current_user.present? %>
  <header class="main-header d-flex align-items-center">
    <div id="flashMessage">
      <%= render 'layouts/flash_messages' %>
    </div>
    <!-- Sidebar toggle button-->
    <div class="logo mr-auto">
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"><span class="sr-only">Toggle
          navigation</span>
      </a>
      <span class="fw-600"><%= @current_user&.email %></span>
    </div>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top navbar-expand-md navbar-light">
      <h5 class="navbar-top-title text-darkgray1 fw-500 text-uppercase mb-0">
      </h5>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
          <i class="fa fa-ellipsis-v"></i>
        </span>
      </button>
      <!-- Navbar Right Menu -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a href="javascript:;" class="nav-link dropdown-toggle fw-500 d-flex align-items-center" data-toggle="dropdown">
              <div class="nav-circie d-flex align-items-center justify-content-center mr-2">
                <i class="fas fa-user"></i></div>
              <%= current_user&.email %>
            </a>
            <div class="dropdown-menu">
              <%= link_to "Log out", destroy_user_session_path, class: 'dropdown-item', method: :delete %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RikoouuPra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="sidebar-mini admin-wrapper sidebar-collapse">
    <%= image_pack_tag 'basic_logos/loader.gif', id: 'loaderImage', style: 'display: none;' %>
    <div class="sidenav-overlay"></div>
    <div class="wrapper">
      <%= render partial: 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_assign_note_form.html.erb
<div class="modal-scrollable">
  <% if users.present? %>
    <%= collection_check_boxes :note_ids, {}, users, :id, :email do |item| %>
      <div data-filter-item data-filter-name='<%= item.object.email.downcase %>' class="border-bottom py-3 checkbox-area custom-control custom-checkbox m-1" id="category_checkboxes_<%= note.id %>">
        <% note_permissions = note.note_permissions %>
        <%= item.check_box(class: "custom-control-input select_check manual note note_#{note.id}", 'data-value': item.value, id: "note_#{note.id}_item_#{item.object.id}", data: {check_class: '.note', note_id: "#{note.id}"}, checked: note_permissions.pluck(:user_id).include?(item.object.id)) %>
        <%= item.label(class: "custom-control-label fw-500 label_note_#{note.id}", style: "font-weight: 500; color: #111;", 'data-value': item.value, for: "note_#{note.id}_item_#{item.object.id}") %>
      </div>
      <div class="row col-lg-12">
        <%= render 'permission_checkbox', note_id: note.id, user_id: item.object.id %>
      </div>
    <% end %>
  <% else %>
    <div class="text-center mt-4">No Record found.</div>
  <% end %>
</div>

app/views/notes/_assign_permission.html.erb
<div class="modal fade category_model_<%= note.id %>" id="notemodal_<%= note.id %>" tabindex="-1" role="dialog" aria-labelledby="modifiermodalLabel" aria-modal="true" >
  <div class="modal-dialog modal-dialog-centered modal-sm-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header d-block p-0 inquiry-form">
        <div class="d-flex align-items-center p-3">
          <button type="button" class="" data-dismiss="modal" aria-label="Close">
            <%= image_pack_tag 'basic_logos/close.svg', class: 'img-fluid',  width: '45' %>
          </button>
          <div class="text-center w-100">
            <h5 class="modal-title fs-20 fw-500 text-center" id="myModalLabel2">Assign Note to User</h5>
          </div>
        </div>
      </div>
      <div class="modal-body assign-item-category pt-0" id="item-list">
        <%= render 'assign_note_form', users: User.all, note: note %>
      </div>
    </div>
  </div>
</div>

app/views/notes/_form.html.erb
<h2 class="admin-main-title text-darkgray1 fw-600 fs-18 border-bottom pb-2">Note</h2>
<%= form_for(note, html: {"data-parsley-validate": '', class: 'inquiry-form'}) do |f| %>
  <div class="">
    <div class="row pl-0">
      <div class="col-xl-9 col-lg-11">
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group mb-3">
              <label class="asterisk">Title</label>
              <%= f.text_field :title, class: 'form-control', data: { parsley_required_message: 'Please enter Title', parsley_maxlength: "20", parsley_maxlength_message: "Title can contain maximum upto 20 characters" }, required: true %>
              <%#= f.hidden_field :location_id, value: @current_location.id %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6">
            <div class="form-group mb-3">
              <label>Description</label>
              <%= f.text_area :description, class: 'form-control', data: {parsley_maxlength: "10000", parsley_maxlength_message: "Description can contain maximum upto 10000 characters" } %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 col-input  pr-3 pr-md-0 col-sm-5">
            <div class="form-group down-arrow mb-2">
              <%= f.select :tag_ids, options_for_select(Tag.pluck(:name, :id), selected: f.object.tag_ids), {},{ include_blank: "Select Category", class: 'form-control category-filter', multiple: :true, required: :true} %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="d-inline-flex flex-column flex-sm-row">
          <%= f.submit form_button_text, class: 'btn btn-admin mr-sm-4 mb-3 mb-sm-0' %>
          <%= link_to "Cancel" , notes_path , class: 'btn btn-gray' %>
        </div>
      </div>
    </div>
  </div>
<% end%>
<script type="text/javascript">
  $("#note_tag_ids").select2({
    tags: true
  });
</script>

app/views/notes/_list.html.erb
<% if @tags.present? %>
  <% @tags.each do |tag| %>
    <tr class="text-black"><td><b><u><%= tag.name.titleize %></u>(<%= tag.notes.count%>)</b></td></tr>
    <% tag.notes.where(id: current_user.related_notes_ids).each do |note|%>
      <% applicable_actions = note.applicable_actions(current_user.id)%>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.description %></td>
        <td><%= raw tags_data(note) %></td>
        <td class="action-icons">
          <div class="action-area">
            <%= link_to(image_pack_tag("home/ic_edit.svg"), edit_note_path(note)) if applicable_actions.include?(:editable) %>
            <%= link_to(image_pack_tag("home/ic_delete.svg"), note_path(note), class: 'mb-1', title: 'Delete', method: :delete, data: {confirm: 'Are you sure, you want to delete this note?'}) if applicable_actions.include?(:deletable)  %>
            <%= link_to image_pack_tag("home/pr.png"), "#", data: {toggle: "modal", target: "#notemodal_#{note.id}"}, title: 'Permission' if note.user_id.eql?(current_user.id) %>
          </div>
        </td>
      </tr>
      <%= render 'assign_permission', note: note if note.user_id.eql?(current_user.id)%>
    <% end %>
  <% end %>
<% else %>
  <tr>
    <td colspan="3" class="text-center">No records found</td>
  </tr>
<% end %>
<script type="text/javascript">
  $(document).on('change', '.note', function(){
    userID = ($(this).data('user-id') || $(this).val())
    noteID = $(this).data('note-id')
      currentID = "#"+$(this).data('id')
      viewable_val = $("#view_"+userID).is(':checked')
      editable_val = $("#edit_"+userID).is(':checked')
      deletable_val = $("#delete_"+userID).is(':checked')
      debugger
    $.ajax({
      url: '/notes/'+noteID+'/note_permissions',
      type: "PUT",
      data: { 
              user_id: userID, 
              note_id: noteID,
              viewable: viewable_val,
              editable: editable_val,
              deletable: deletable_val
            }
    })
  })
</script>

app/views/notes/_permission_checkbox.html.erb
<% note_permission = NotePermission.find_by_user_id(user_id) %>
  <div class="checkbox-area custom-control custom-checkbox admin-border pb-2 mb-3">
    <%= check_box_tag "view_#{user_id}", 'yes', false, class: "custom-control-input viewable note", data: {note_id: note_id, user_id: user_id, check_name: 'viewable', id: "view_#{user_id}"}, checked: note_permission&.viewable? ? true : false %>
    <label class="custom-control-label col-md-3 mr-3" for="view_<%=user_id%>">View</label>
  </div>
  <div class="checkbox-area custom-control custom-checkbox admin-border pb-2 mb-3">
    <%= check_box_tag "edit_#{user_id}", 'yes', false, class: "custom-control-input editable note", data: {note_id: note_id, user_id: user_id, check_name: 'editable', id: "edit_#{user_id}"}, checked: note_permission&.editable? ? true : false %>
    <label class="custom-control-label  col-md-3 mr-3" for="edit_<%=user_id%>">Edit</label>
  </div>
  <div class="checkbox-area custom-control custom-checkbox admin-border pb-2 mb-3">
    <%= check_box_tag "delete_#{user_id}", 'yes', false, class: "custom-control-input deletable note", data: {note_id: note_id, user_id: user_id, check_name: 'deletable', id: "delete_#{user_id}"}, checked: note_permission&.deletable? ? true : false %>
    <label class="custom-control-label col-md-3 mr-3" for="delete_<%=user_id%>">Delete</label>
  </div>

app/views/notes/edit.html.erb
<section class="content-wrapper">
  <div class="row">
    <div class="col-xl-10 col-lg-9 pl-3 pl-lg-0">
      <div class="content">
        <h2 class="admin-main-title text-darkgray1 fw-600 fs-20 border-bottom mb-4 pb-2">Add New Note</h2>
        <%= render 'form', note: @note %>
      </div>
    </div>
  </div>
</section>

app/views/notes/index.html.erb
 <section class="content-wrapper">
  <div class="row">
    <div class="col-xl-12 col-lg-12 pl-3 pl-lg-0">
      <div class="content">
        <h2 class="admin-main-title text-darkgray1 fw-600 fs-20 border-bottom mb-4 pb-2">Notes
          <%= link_to 'Add New Item', new_note_path, class: "btn btn-admin pull-right", style:'float: right; margin-top:-13px;'%></h2>
        <div class="mt-2">
          <div class="row">
            <div class="col-sm-12">
              <div class="admin-table bg-white table-responsive mt-4">
                <table class="table table-bordered">
                  <thead class="thead-dark">
                    <tr>
                      <th width="20">Name</th>
                      <th width="50%">Description</th>
                      <th>Tags</th>
                      <th width="30%" class="text-center">Actions</th>
                    </tr>
                  </thead>
                  <tbody class="categories_list">
                    <%= render 'list' %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<section>

app/views/notes/new.html.erb
<section class="content-wrapper">
  <div class="row">
    <div class="col-xl-10 col-lg-9 pl-3 pl-lg-0">
      <div class="content">
        <h2 class="admin-main-title text-darkgray1 fw-600 fs-20 border-bottom mb-4 pb-2">Add New Note</h2>
        <%= render 'form', note: @note %>
      </div>
    </div>
  </div>
</section>

app/views/notes/note_permissions.js.erb
$('#flashMessage').html("<%= j render 'layouts/flash_messages' %>");
$("notemodal_<%= params[:note_id]").modal('hide')